### ISSUE TITLE
stocktalk이 유니코드를 지원 안하네

### ISSUE THREAD

**Issue by LimeCitron** [17-1-SKKU-OSS/095A#1]
ㅠㅠ

**Comment by NahahaNahaha** [comment]
ㅠㅠ화나네요!

**Comment by LimeCitron** [comment]
방법 찾았어

#-*- coding: utf-8 -*-
from stocktalk import streaming
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

소스 코드 젤 위의 

from stocktalk import streaming 

부분을

위처럼 바꿔주면 한글도 검색이 된다.

**Comment by LimeCitron** [comment]
다만 완벽한건 아니고 가끔 관련없는 다른 나라 언어까지 딸려오는 경우도 있다. 그리고 한글 트윗 자체가 많은편이  아니라서 영어 검색에 비해 검색률은 낮네.

**Comment by LimeCitron** [comment]
다른 나라 언어 오류의 경우 오류가 아니라 원래 쿼리 제목까지 검색이 되게 만든 거였어.
