### ISSUE TITLE
현재 변수를 한 개로 바꾼후 검색 단어를 한 개로 할 시

### ISSUE THREAD

**Issue by NahahaNahaha** [17-1-SKKU-OSS/095A#4]
오류가 발생함 원하는 단어가 검색이 되지 않고 단어를 지정하는 변수명이 검색됌

**Comment by NahahaNahaha** [comment]
문제점을 찾음 
변수명이 글자수가 5개 일 때 문제가 생김 
변수명의 글자 수가 4개일 때 문제가 사라짐 
3개 이하일 때도 해보게ㅆ음

**Comment by LimeCitron** [comment]
변수 1개 잘 됨. 이거 이슈는 닫는다. ㅎㅎㅎ
