### ISSUE TITLE
변수명의 글자 크기가 6글자일 경우

### ISSUE THREAD

**Issue by NahahaNahaha** [17-1-SKKU-OSS/095A#5]
6글자 보다 클 때는 모르겟지만 
6글자일 때는 오류 발생 
터미널에 Got an error with status code: 420

**Comment by LimeCitron** [comment]
MIMA = ['MIMA', 'pasta']
MOON = ['MOON', 'moon']
DAY = ['DAY', 'day']
GOGOGO = ['GOGOGO', 'garden']
MEMEME = ['MEMEME', 'bridge']


tickers = [MIMA, MOON, DAY, GOGOGO, MEMEME] 
queries =  MIMA+MOON+DAY+GOGOGO+MEMEME 
refresh = 30                  


이 코드로 했을 때 정상적으로 돌아가는데?

이거 좀더 연구해봐야할 듯.

**Comment by LimeCitron** [comment]
420 오류는 트위터 API 공통 오류같아. 

https://httpstatusdogs.com/420-enhance-your-calm 

참조.
